version: 1
default_environment: dev
project_id: 9275ae68-5e4b-4593-827b-7ae6df013df8
environments:
- name: dev
- name: staging
- name: prod
plugins:
  utilities:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.3.0 dbt-duckdb~=1.3.0 git+https://github.com/meltano/dbt-ext.git@main
    config:
      project_dir: $MELTANO_PROJECT_ROOT
      profiles_dir: $MELTANO_PROJECT_ROOT/profiles
      path: $MELTANO_PROJECT_ROOT/output/duckdb-local.db
  - name: evidence
    namespace: evidence
    settings_group_validation:
    # Defines required config
    - - home_dir
    settings:
    - name: home_dir
      env: EVIDENCE_HOME_DIR
    config:
      home_dir: ./reports
    commands:
      install:
        executable: npm
        args: --prefix $EVIDENCE_HOME_DIR install
      dev:
        executable: npm
        args: --prefix $EVIDENCE_HOME_DIR run dev
jobs:
- name: full-build
  tasks:
  - dbt-duckdb:seed
  - dbt-duckdb:run
  - evidence:install
  - evidence:dev
